# Generated by Django 4.1 on 2022-08-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=250, null=True)),
                ('estado', models.CharField(max_length=250)),
                ('bairro', models.CharField(max_length=250)),
                ('rua', models.CharField(max_length=250, null=True)),
                ('complemento', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
