# Generated by Django 4.1 on 2022-08-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cep',
            name='estado',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cep',
            name='rua',
            field=models.CharField(max_length=250),
        ),
    ]
