name: Django CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install -r requirements-dev.txt
    - name: Lint com Flake8
      run: |
         flake8
    - name: Copiando arquivo de configuração
      run: |
          cp .env-sample .env
#    - name: Testes de aplicação com Pytest
#      run: |
#        pytest
